// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/bborbe/time"
)

type CurrentDateTimeSetter struct {
	SetNowStub        func(time.DateTime)
	setNowMutex       sync.RWMutex
	setNowArgsForCall []struct {
		arg1 time.DateTime
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CurrentDateTimeSetter) SetNow(arg1 time.DateTime) {
	fake.setNowMutex.Lock()
	fake.setNowArgsForCall = append(fake.setNowArgsForCall, struct {
		arg1 time.DateTime
	}{arg1})
	stub := fake.SetNowStub
	fake.recordInvocation("SetNow", []interface{}{arg1})
	fake.setNowMutex.Unlock()
	if stub != nil {
		fake.SetNowStub(arg1)
	}
}

func (fake *CurrentDateTimeSetter) SetNowCallCount() int {
	fake.setNowMutex.RLock()
	defer fake.setNowMutex.RUnlock()
	return len(fake.setNowArgsForCall)
}

func (fake *CurrentDateTimeSetter) SetNowCalls(stub func(time.DateTime)) {
	fake.setNowMutex.Lock()
	defer fake.setNowMutex.Unlock()
	fake.SetNowStub = stub
}

func (fake *CurrentDateTimeSetter) SetNowArgsForCall(i int) time.DateTime {
	fake.setNowMutex.RLock()
	defer fake.setNowMutex.RUnlock()
	argsForCall := fake.setNowArgsForCall[i]
	return argsForCall.arg1
}

func (fake *CurrentDateTimeSetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CurrentDateTimeSetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ time.CurrentDateTimeSetter = new(CurrentDateTimeSetter)
